# Generated by Django 3.2.8 on 2021-10-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_rename_color_code_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='title',
            field=models.CharField(default='#CODE', max_length=100),
        ),
    ]
