# Generated by Django 3.2.8 on 2021-11-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0003_code_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
    ]
